import { EmailAuthProvider, getAuth, GoogleAuthProvider, signOut } from "firebase/auth";
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useAuthState } from 'react-firebase-hooks/auth';
import StyledFirebaseAuth from "react-firebaseui/StyledFirebaseAuth";
import { BACKEND_URL } from '../shared/constants';
import styles from '../styles/Home.module.css';


const Home: NextPage = () => {
    const [user, loading, error] = useAuthState(getAuth());

    if (loading) {
        return null;
    }

    const test = () => {
        alert(BACKEND_URL);

        fetch(BACKEND_URL + "api/Demo").then(async result => {
            alert(result.statusText);
            console.log(result)
            console.log(await result.json())
        });
    };

    const uiConfig: firebaseui.auth.Config = {
        // Popup signin flow rather than redirect flow.
        signInFlow: 'popup',
        // Redirect to /signedIn after sign in is successful. Alternatively you can provide a callbacks.signInSuccess function.
        signInSuccessUrl: '/',
        callbacks: {
            signInSuccessWithAuthResult: (result, redirect) => {
                console.log(result);
                return true;
            },
            signInFailure: (error) => {
                console.error(error);
            }
        },
        // We will display Google and Facebook as auth providers.
        signInOptions: [
            GoogleAuthProvider.PROVIDER_ID,
            EmailAuthProvider.PROVIDER_ID,
        ],
    };

    if (!user) {
        return (
            <>
                Not signed in <br />
                <StyledFirebaseAuth firebaseAuth={getAuth()} uiConfig={uiConfig}></StyledFirebaseAuth>
            </>
        );
    }
    else {
        return (<>
            Signed in with {user.displayName ?? user.email}<br />
            <button onClick={() => signOut(getAuth())}>Sign out</button>
        </>);
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <span onClick={test}>Peperino</span> powered by <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/index.tsx</code>
                </p>

                <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>Find in-depth information about Next.js features and API.</p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>Learn about Next.js in an interactive course with quizzes!</p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/canary/examples"
                        className={styles.card}
                    >
                        <h2>Examples &rarr;</h2>
                        <p>Discover and deploy boilerplate example Next.js projects.</p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>
                            Instantly deploy your Next.js site to a public URL with Vercel.
                        </p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
