# dart run build_runner build
targets:
  $default:
    sources:
      - lib/**
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/api/_swagger"
          output_folder: "lib/api/_generated/"
          # use_path_for_request_names: false
          # nullable_models:
          #   - "RoomOutDto"
